Update WSA_Build.yml

diff --git a/.github/workflows/WSA_Build.yml b/.github/workflows/WSA_Build.yml
--- a/.github/workflows/WSA_Build.yml
+++ b/.github/workflows/WSA_Build.yml
@@ -69,9 +69,10 @@ jobs:
         uses: sn-o-w/cache-apt-pkgs-action@master
         with:
           packages: sudo ca-certificates qemu-utils setools lzip patchelf e2fsprogs python3 python3-venv python3-pip aria2 p7zip-full attr unzip
+          version: 1.0
           
       - name: Install Lzip + Python venv & its libraries 🐍
-
+        working-directory: MagiskOnWSALocal
         run: |
 
           wget -P ./download/ http://ftp.debian.org/debian/pool/main/l/lzip/lzip_1.23-5_amd64.deb
@@ -100,11 +101,11 @@ jobs:
 
           source "$(dirname "$PWD")/python3-env/bin/activate" || abort "Failed to activate python3 virtual env"
 
-          python3 -c "import pkg_resources; pkg_resources.require(open('MagiskOnWSALocal/scripts/requirements.txt',mode='r'))" &>/dev/null || {
+          python3 -c "import pkg_resources; pkg_resources.require(open('scripts/requirements.txt',mode='r'))" &>/dev/null || {
 
                echo "Installing Python3 dependencies"
 
-               python3 -m pip install -r MagiskOnWSALocal/scripts/requirements.txt || abort "Failed to install python3 dependencies"
+               python3 -m pip install -r scripts/requirements.txt || abort "Failed to install python3 dependencies"
 
           }
 
