Update WSA_Build.yml

diff --git a/.github/workflows/WSA_Build.yml b/.github/workflows/WSA_Build.yml
--- a/.github/workflows/WSA_Build.yml
+++ b/.github/workflows/WSA_Build.yml
@@ -82,12 +82,12 @@ jobs:
            source "$PYTHON_VENV_DIR"/bin/activate || abort "Failed to activate python3 virtual env"
            python3 -c "import pkg_resources; pkg_resources.require(open('requirements.txt',mode='r'))" &>/dev/null || {
              echo "Installing Python3 dependencies"
-             python3 -m pip install -r requirements.txt || abort "Failed to install python3 dependencies"
+             python3 -m pip install -r scripts/requirements.txt || abort "Failed to install python3 dependencies"
          
            }
             deactivate
            else
-             python3 -m pip install -r requirements.txt -q || abort "Failed to install python3 dependencies"
+             python3 -m pip install -r scripts/requirements.txt -q || abort "Failed to install python3 dependencies"
            fi
 
       - name: Build WSA
