Update WSA_Build.yml

diff --git a/.github/workflows/WSA_Build.yml b/.github/workflows/WSA_Build.yml
--- a/.github/workflows/WSA_Build.yml
+++ b/.github/workflows/WSA_Build.yml
@@ -69,8 +69,26 @@ jobs:
         run: |
           sudo apt-get update
           sudo apt-get install -y sudo ca-certificates qemu-utils setools lzip patchelf e2fsprogs python3 python3-venv python3-pip aria2 p7zip-full attr xz-utils unzip
-          python3 -m venv
-          python3 -m pip install -r scripts/requirements.txt -v
+          python_version=$(python3 -c 'import sys;print("{0}{1}".format(*(sys.version_info[:2])))')
+          if [ "$python_version" -ge 311 ]; then
+            python3 -c "import venv" >/dev/null 2>&1 || if ! ($SUDO "$PM" "${INSTALL_OPTION[@]}" "python3-venv"); then abort; fi
+            PYTHON_VENV_DIR="$(dirname "$PWD")/python3-env"
+            [ -f "$PYTHON_VENV_DIR/bin/activate" ] || {
+              echo "Creating python3 virtual env"
+              python3 -m venv "$PYTHON_VENV_DIR" || abort "Failed to create python3 virtual env"
+
+           }
+
+           source "$PYTHON_VENV_DIR"/bin/activate || abort "Failed to activate python3 virtual env"
+           python3 -c "import pkg_resources; pkg_resources.require(open('requirements.txt',mode='r'))" &>/dev/null || {
+             echo "Installing Python3 dependencies"
+             python3 -m pip install -r requirements.txt || abort "Failed to install python3 dependencies"
+         
+            }
+            deactivate
+           else
+             python3 -m pip install -r requirements.txt -q || abort "Failed to install python3 dependencies"
+           fi
 
       - name: Build WSA
         id: build_wsa
